# Generated by Django 6.0.5 on 2026-05-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_savedblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='savedBlog',
        ),
    ]
